### ISSUE TITLE
postprocessing of solutions

### ISSUE THREAD

**Issue by kkmann** [kkmann/otsd#13]
we need to round the n1/n2 part after optimization and then refit the remaining parameters. This is a heuristic, but probably the best one can do...

**Comment by kkmann** [comment]
I think we can start thinking about this now, maybe you could give it a try @MatheMax after we got #29 sorted out. 

The easiest approximation would be to simply round the pivot points to integers - during the optimization procedure, however, we currently assume that the scores are smooth polynomial functions - this is no longer the case if we treat n2 as a piecewise constant step function!
My hope would be that this should not be a major issue if the overall sample sizes are fairly large but we should investigate how problematic this could become and come up with a way to return proper, integer n1/n2 in a consistent way.

Any suggestions?

**Comment by MatheMax** [comment]
I fear that rounding during optimization could yield weird results because we lose continuity.

But when we assume the problem to be continuous, we could round n1 and n2 after optimization and then start a second optimization with these values fixed and the obtained c-values as starting values to modify the c-values. This should imply only small changes and therefore converge quickly.

What do you think?

**Comment by kkmann** [comment]
wasn't suggesting to round during optimization:

1. optimize assuming everything is continuous
2. round all sample sizes to integers
3. reoptimize keeping sample sizes fixed to rounded values

In 3. we still assume that n2 can be described as a polynomial - which it can't since the true n2 function must map to integers only. This might screw up error rate control. Also, we need a method to return the rounded version of n2 for final use...

**Comment by MatheMax** [comment]
Done with pr #35
